"""Create initial Asset and PriceSnapshot tables

Revision ID: 146f5d05fbeb
Revises: 
Create Date: 2025-12-10 21:49:47.176619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '146f5d05fbeb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.Column('average_buy_price', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index(op.f('ix_Asset_id'), 'Asset', ['id'], unique=False)
    op.create_table('PriceSnapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['Asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PriceSnapshot_timestamp'), 'PriceSnapshot', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_PriceSnapshot_timestamp'), table_name='PriceSnapshot')
    op.drop_table('PriceSnapshot')
    op.drop_index(op.f('ix_Asset_id'), table_name='Asset')
    op.drop_table('Asset')
    # ### end Alembic commands ###
